source "http://rubygems.org"

gem "rake"
gem "cucumber"
gem "rspec"
gem "page-object"
gem "require_all"
gem "fig_newton"
gem "simplecov"
gem "data_magic"
gem "selenium-webdriver"
gem "watir-webdriver"